name: release
on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write
jobs:
  test:
    uses: "kubeshop/kube-webhook-certgen/.github/workflows/test.yaml@master"
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
        with:
          fetch-depth: 0
      - name: "Golang"
        uses: "actions/setup-go@v3"
        with:
          go-version: "1.19"
      - name: "Set up Docker Buildx"
        uses: "docker/setup-buildx-action@v2"
      - name: "Login"
        uses: "docker/login-action@v2"
        with:
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"
      - name: "Release"
        uses: "goreleaser/goreleaser-action@v3"
        with:
          distribution: "goreleaser"
          version: "latest"
          args: "-f ./.goreleaser.yml release --rm-dist"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
